# bootstrap the instances to have python for ansible to run modules
# - hosts: tag_App_pathfinder_character_tool
#   gather_facts: false
#   tasks:
#     - name: Install Python
#       raw: "apt-get -y -q install python"
#       become: true
#       become_method: "sudo"

# hosts is really just the local instance since it is being called through the provider
- hosts: all
  vars:
    nodejs_version: "6.x"
  roles:
    - geerlingguy.nodejs
  become: true
  become_method: "sudo"

- hosts: all
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "{{fqdn}}"
        extra_parameters: |
          location / {
              proxy_pass http://localhost:3000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
  roles:
    - geerlingguy.nginx
  become: true

- hosts: all
  roles:
    - node_app
  become: true
  become_method: "sudo"

