# bootstrap the instances to have python for ansible to run modules
# - hosts: tag_App_pathfinder_character_tool
#   gather_facts: false
#   tasks:
#     - name: Install Python
#       raw: "apt-get -y -q install python"
#       become: true
#       become_method: "sudo"

- hosts: all
  roles:
    - app