# hosts is really just the local instance since it is being called through the provider
- hosts: all
  roles:
    - base
  become: true
  become_method: "sudo"

- hosts: all
  vars:
    nodejs_version: "6.x"
  roles:
    - geerlingguy.nodejs
  become: true
  become_method: "sudo"

- hosts: all
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "{{uifqdn}}"
        extra_parameters: |
          location / {
              proxy_pass http://localhost:3000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      - listen: "80"
        server_name: "{{apifqdn}}"
        extra_parameters: |
          location / {
              root {{ui_dir}}/dist/static;
          }
  roles:
    - geerlingguy.nginx
  become: true

- hosts: all
  roles:
    - pathfinder
  become: true
  become_method: "sudo"



