---
- file:
    path: "{{api_dir}}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0544

- file:
    path: "{{ui_dir}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0744

- name: Get ui artifact
  s3:
    bucket: "{{sw_releases_bucket}}"
    object: "/{{app_name}}-ui/{{app_name}}-ui-{{ui_version}}.tar.gz"
    dest: "{{ui_artifact_path}}"
    mode: get

- name: unarchive ui artifact
  unarchive:
    remote_src: yes
    src: "{{ui_artifact_path}}"
    dest: "{{ui_dir}}"
    owner: www-data
    group: www-data

- name: Get api artifact
  s3:
    bucket: "{{sw_releases_bucket}}"
    object: "/{{app_name}}-api/{{app_name}}-api-{{api_version}}.tar.gz"
    dest: "{{api_artifact_path}}"
    mode: get

- name: unarchive api artifact
  unarchive:
    remote_src: yes
    src: "{{api_artifact_path}}"
    dest: "{{api_dir}}"
    owner: ubuntu
    group: ubuntu

- template:
    src: service.j2
    dest: "/etc/init/{{app_name}}.conf"
    owner: root
    group: root
    mode: 0644

- service:
    name: "{{app_name}}"
    state: started
    enabled: yes

# - include: _notify_via_sms.yaml
# - name: Send notification messages via SNS with short message for SMS
#   local_action:
#     module: sns
#     msg: "{{ inventory_hostname }} has completed the play."
#     sms: "deployed!"
#     subject: "Deploy complete!"
#     topic: "deploy"
# aws sns publish --phone-number +16626940191 --message "Ready: http://${PUBLIC_HOSTNAME}:3000"

