---
- file:
    path: "{{app_dir}}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0744

- name: Get artifact
  s3:
    bucket: "{{sw_releases_bucket}}"
    object: "/{{app_name}}/{{app_name}}-{{app_version}}.tar.gz"
    dest: "{{artifact_path}}"
    mode: get

- unarchive:
    remote_src: yes
    src: "{{artifact_path}}"
    dest: "{{app_dir}}"
    owner: ubuntu
    group: ubuntu

- template:
    src: service.j2
    dest: "/etc/init/{{app_name}}.conf"
    owner: root
    group: root
    mode: 0644

- service:
    name: "{{app_name}}"
    state: started
    enabled: yes

# - include: _notify_via_sms.yaml
# - name: Send notification messages via SNS with short message for SMS
#   local_action:
#     module: sns
#     msg: "{{ inventory_hostname }} has completed the play."
#     sms: "deployed!"
#     subject: "Deploy complete!"
#     topic: "deploy"
# aws sns publish --phone-number +16626940191 --message "Ready: http://${PUBLIC_HOSTNAME}:3000"

