name 'pathfinder'
maintainer 'Jake Gaylor'
maintainer_email 'jhgaylor@gmail.com'
license 'all_rights'
description 'Installs/Configures pathfinder'
long_description 'Installs/Configures pathfinder'
version '0.1.0'

depends 'nginx'
depends 'tar'