name 'base'
maintainer 'Jake Gaylor'
maintainer_email 'jhgaylor@gmail.com'
license 'all_rights'
description 'Installs/Configures base'
long_description 'Installs/Configures base'
version '0.1.0'

depends 'apt'
depends 'awscli'
