---

- include: _awscli.yaml

- include: _deploy_artifact.yaml

# - include: _notify_via_sms.yaml
# - name: Send notification messages via SNS with short message for SMS
#   local_action:
#     module: sns
#     msg: "{{ inventory_hostname }} has completed the play."
#     sms: "deployed!"
#     subject: "Deploy complete!"
#     topic: "deploy"
# aws sns publish --phone-number +16626940191 --message "Ready: http://${PUBLIC_HOSTNAME}:3000"

